dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: zookeeper://127.0.0.1:2181      
  protocol:
    name: dubbo
    serialization: hessian2
    port: 20881
  consumer:
    timeout: 1000
server:
  port: 9091
spring:
  application:
    name: dubbo-consumer